<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>F1_simulation</RootNamespace>
    <UserSecretsId>7012ed20-b8f5-48cf-afb1-e45e9694d31b</UserSecretsId>

    <!-- Prevent SDK from generating assembly attributes -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="MySql.Data" Version="9.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <Company>Vyom Chamaria</Company>
    <Product>F1 Simulation</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>

</Project>
